version: "2.4"
services:
  db:
    image: postgres:14
    restart: "no"
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    # network_mode: host  # host 네트워크 모드 제거
    ports:
      - '5432:5432'

  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: "no"
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}
      DB_DATABASE: ${DB_DATABASE}
      OTP_URL: http://host.docker.internal:8080
      TZ: Asia/Seoul
    # network_mode: host  # host 네트워크 모드 제거
    volumes:
      - .:/app
      - /etc/localtime:/etc/localtime:ro
    cpus: 1.0
    mem_limit: 4g
    command: npm run start:dev
    depends_on:
      - db
    ports:
      - '3000:3000'

volumes:
  postgres-data: 